config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Only allow authenticated users to get access
  # to the Sidekiq web interface
  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#landing'
  get '/email_template', to: 'home#email_template', as: 'email_template'
  get '/about', to: 'home#about', as: 'about'
  get '/contact', to: 'home#contact', as: 'contact'
  get '/animation', to: 'home#animation'
  get '/use_reference', to: 'home#use_reference', as: 'reference'

  resources :messages do
    member do
      get :profile
    end
  end

  resources :users, shallow: true do
    collection do
      get :notifications
      post :mark_notification_read
      patch :update_referral_code
    end
    member do
      get :show_verify
      post :verify
      post :resend
      get :change_password
      patch :update_password
      patch :deactivate_account
      patch :activate_account
      patch :toggle_text_alert
      patch :toggle_advanced_search
    end
  end

  resources :orders, except: %i[edit update destroy] do
    member do
      post :success
      post :fail
      post :cancel
    end
  end

  resources :partner_preferences do
  end

  resources :marriage_profiles do
    collection do
      get :blocked_profiles
      get :pending_profiles
      get :requested_profiles
      get :refferel_code
    end
    member do
      get :profile_info
      get :dashboard
      get :switch
      get :edit_about
      patch :update_about
      post :send_request
      patch :accept_request
      patch :reject_request
      patch :cancel_request
      patch :remove_profile
      patch :block_profile
      patch :unblock_profile
      patch :change_profile
      patch :change_photo
      get :requested_profiles
      get :search_page
      get :search
      post :search
    end
  end

  resources :advertiser_profiles
  resources :occupations
  resources :appearances
  resources :family_members
  resources :marriage_informations
  resources :life_styles
  resources :hobbies_and_interests
  resources :cultural_values
  resources :academic_informations
  resources :favourites do
    collection do
      delete :remove
    end
  end

  resources :blogs
  resources :market_places
  resources :terms_of_uses
  resources :privacy_policies
  resources :faqs
  resources :assisted_services
  resources :precautionary_measures
  resources :process_flows, as: :how_it_works, path: :how_it_works
  resources :customer_supports
  resources :privacy_settings do
    member do
      put :toggle_update
    end
  end
  resources :chat_friendships do
    member do
      post :send_request
      patch :accept_request
      patch :reject_request
    end
  end
end

app/views/shared/_about.html.erb
<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  About Us
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
  <%= render partial: 'shared/about_item',
             collection: About.all.order(:display_order), as: :about %>
</div>

app/views/shared/_about_content.html.erb
<% if about_content.present? %>
  <div class="container about-container">
    <div class="row">
      <div class="col-md-12">
        <div id="accordion" role="tablist" aria-multiselectable="true"
             class="card-collapse">
          <%= render partial: 'shared/dynamic_about_content',
                     collection: about_content,
                     as: :about
          %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'shared/default_content' %>
<% end %>

app/views/shared/_about_item.html.erb
<a class="dropdown-item"
   href="<%= about_path + "/#heading_#{about.id}" %>">
  <%= about.content_type %>
</a>

app/views/shared/_after_login_nav.html.erb
<ul class="navbar-nav mr-auto custom-navbar-nav d-flex flex-row align-items-center">
  <li class="nav-item dropdown p-2 flex-fill">
    <%= render 'shared/about' %>
  </li>
  <li class="nav-item dropdown p-2 flex-fill">
    <%= render 'shared/market_place_menu' %>
  </li>
  <li class="nav-item dropdown p-2 flex-fill">
    <%= render 'shared/assisted_services_menu' %>
  </li>
  <li class="nav-item p-2 flex-fill">
    <a class="nav-link" href="<%= how_it_works_path %>">
      How It Works
    </a>
  </li>
</ul>

<ul class="navbar-nav d-flex flex-row align-items-center">

  <% unless current_user.self? || current_user.other_as_matchmaker? %>
    <li class="nav-item dropdown p-2 flex-fill">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Switch Profile
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <% if current_user.marriage_profiles.present? %>
          <% current_user&.marriage_profiles&.each do |profile| %>
            <a class="dropdown-item" href="<%= profile.persisted? ? switch_marriage_profile_path(profile) : '#' %>"> <%= profile&.name || profile&.unique_id %> </a>
          <% end %>
        <% end %>
      </div>
    </li>
  <% end %>

  <li class="nav-item p-2 flex-fill">
    <a class="nav-link" href="<%= (current_user.present? && current_active_profile.present?) ? search_page_marriage_profile_path(current_active_profile) : '#' %>">
      <i class="fa fa-search" aria-hidden="true"></i>
    </a>
  </li>

  <li class="nav-item dropdown p-2 flex-fill notification" title="<%= current_user.notification_msg %>">
    <%= link_to '#show-notification', class: 'nav-link dropdown-toggle text-gray', role: 'button', data: {toggle: 'dropdown'}, 'aria-haspopup': true, 'aria-expanded': false do %>
      <i class="fas fa-bell"></i>
      <span class="notification-counter"><%= current_user&.notifications&.unread&.count&.zero? ? '' : current_user&.notifications&.unread&.count %></span>
    <% end %>

    <div class="dropdown-menu row js-notification-list" aria-labelledby="navbarDropdownMenuLink">
      <% if current_user&.notifications.count > 0 %>
        <%= render partial: 'users/notification', collection: current_user&.notifications&.order(:is_read, created_at: :desc) %>
      <% else %>
        <p class="text-center">No notification</p>
      <% end %>
    </div>
  </li>

  <li class="border-right p-2 nav-item flex-fill"></li>

  <li class="nav-item dropdown p-2 flex-fill">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= image_tag current_active_profile.present? && current_active_profile.profile_image.present? ? current_active_profile.profile_image.url(:header_small_thumb) : 'bk.png', width: '21', height: '21', class: 'rounded-circle' %>
    </a>
    <div class="dropdown-menu dashboard-nav" aria-labelledby="navbarDropdownMenuLink">

      <%= link_to root_path, class: 'dropdown-item' do %>
        <div class="col-12 p-1">
          <div class="row">
            <div class="col-2 p-0">
              <i class="fa fa-home"></i>
            </div>
            <div class="col-10 p-0">
              Home
            </div>
          </div>
        </div>
      <% end %>

      <%= link_to (current_user.marriage_profiles.present? && current_active_profile.present?) ? dashboard_marriage_profile_path(current_active_profile) : '#', class: 'dropdown-item' do %>
        <div class="col-12 p-1">
          <div class="row">
            <div class="col-2 p-0">
              <i class="fa fa-tachometer"></i>
            </div>
            <div class="col-10 p-0">
              Dashboard
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to current_active_profile.present? ? profile_info_marriage_profile_path(current_active_profile) : '#', class: 'dropdown-item' do %>
        <div class="col-12 p-1">
          <div class="row">
            <div class="col-2 p-0">
              <i class="fa fa-user"></i>
            </div>
            <div class="col-10 p-0">
              Profile
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to privacy_settings_path, class: 'dropdown-item' do %>
        <div class="col-12 p-1">
          <div class="row">
            <div class="col-2 p-0">
              <i class="fa fa-user-cog"></i>
            </div>
            <div class="col-10 p-0">
              Privacy Settings
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to customer_supports_path, class: 'dropdown-item' do %>
        <div class="col-12 p-1">
          <div class="row">
            <div class="col-2 p-0">
              <i class="fas fa-headset"></i>
            </div>
            <div class="col-10 p-0">
              Reported Issues
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to faqs_path, class: 'dropdown-item' do %>
        <div class="col-12 p-1">
          <div class="row">
            <div class="col-2 p-0">
              <i class="fa fa-question-circle"></i>
            </div>
            <div class="col-10 p-0">
              FAQ
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to precautionary_measures_path, class: 'dropdown-item' do %>
        <div class="col-12 p-1">
          <div class="row">
            <div class="col-2 p-0">
              <i class="fas fa-exclamation-circle"></i>
            </div>
            <div class="col-10 p-0">
              Precautionary Measures
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
        <div class="col-12 p-1">
          <div class="row">
            <div class="col-2 p-0">
              <i class="fas fa-sign-out-alt"></i>
            </div>
            <div class="col-10 p-0">
              Log Out
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </li>
</ul>

app/views/shared/_before_login_nav.html.erb
<ul class="navbar-nav mr-auto custom-navbar-nav">
  <li class="nav-item dropdown">
    <%= render 'shared/about' %>
  </li>
  <li class="nav-item dropdown">
    <%= render 'shared/market_place_menu' %>
  </li>
  <li class="nav-item dropdown">
    <%= render 'shared/assisted_services_menu' %>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Blogs
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
      <a class="dropdown-item" href="<%= blogs_path type: "success_story" %>">
        Success Stories
      </a>
      <a class="dropdown-item" href="<%= blogs_path %>">
        All Blogs
      </a>
    </div>
  </li>
</ul>
<ul class="navbar-nav d-flex flex-row align-items-center">
  <li class="nav-item flex-fill p-2">
    <a class="nav-linkx text-white btn btn-sm nav-login-btn" href="#" data-toggle="modal" data-target="#loginModal">
      LOGIN </a>
  </li>

  <li class="nav-item dropdown help-dropdown p-2 flex-fill">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Help
    </a>
    <div class="dropdown-menu landing-nav" aria-labelledby="navbarDropdownMenuLink">
      <a class="dropdown-item" href="<%= faqs_path %>">
        <i class="fa fa-question-circle"></i> FAQ
      </a>
      <a class="dropdown-item" href="<%= precautionary_measures_path %>">
        <i class="fas fa-exclamation-circle"></i> Precautionary Measures
      </a>
      <a class="dropdown-item" href="<%= how_it_works_path %>">
        <i class="fas fa-cogs"></i> How It Works
      </a>
    </div>
  </li>
</ul>

app/views/shared/_contact_content.html.erb
<div class="col-md-12 white-background p-4 mt-2 blog-section">
  <div class="text-justify pb-2 mt-3 merriweather">
    <strong>
      <%= contact&.heading %>
    </strong>
  </div>
  <div class="text-justify">
    <p><%= contact&.content %></p>
  </div>
</div>

<div class="col-md-12 white-background p-4 mt-2 blog-section mb-5 merriweather">
  <div class="">
    <strong>Email Address : </strong> <%= contact&.contact %>
  </div>
</div>

app/views/shared/_header.html.erb
<section class=" section_1 container-fluid p-0 bk-full-header">
  <div class="bk-header fixed-top">
    <div class="container">
      <header>
        <nav class="navbar navbar-expand-lg navbar-light">
          <a href="" class="custom-navbar-toggler navbar-toggler openbtn" onclick="openNav()" data-toggle="collapse" data-target="#navbarNavxx" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"> </span>
          </a>

          <a class="navbar-brand" href="<%= (user_signed_in? && current_active_profile.present?) ? dashboard_marriage_profile_path(current_active_profile) : root_path %>">
            <%= image_tag 'bk_logo.webp', class: 'bk-header-logo', alt: 'Logo' %>
          </a>

          <div class="mobile-nav-login-btn">
            <% if user_signed_in? %>
              <a class="text-white btn btn-sm nav-login-btn" href="<%=  destroy_user_session_path %>" data-method="delete">
                Logout
              </a>
            <% else %>
              <a class="text-white btn btn-sm nav-login-btn" href="#" data-toggle="modal" data-target="#loginModal">
                LOGIN
              </a>
            <% end %>
          </div>


          <div class="collapse navbar-collapse" id="navbarNav">
            <% if user_signed_in? %>
              <%= render 'shared/after_login_nav' %>
            <% else %>
              <%= render 'shared/before_login_nav' %>
            <% end %>
          </div>
        </nav>
      </header>
      <%= render 'shared/mobile_side_panel' %>
    </div>
  </div>

</section>

app/views/shared/_image_cropping_modal.html.erb
<div class="modal fade" id="upload-modal" aria-labelledby="modalLabel" role="dialog" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalLabel">Resize image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <img id="image" src="" alt="Logo">
        </div>
      </div>

      <div class="modal-footer">
        <input type="button" class="btn btn-invite mb5 p5 " id="skip-cropping" value="Skip Cropping" data-dismiss="modal"></button>
        <input type="button" id="page-pic-save" class="btn btn-invite mb5 " value="Save" />
        <button type="button" class="btn btn-invite mb5" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_market_place_menu.html.erb
<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  Wedding Shopping
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
  <% MarketPlaceType&.all&.each do |market_place_type| %>
    <a class="dropdown-item" href="<%= market_places_path(market_place_type: "#{market_place_type.name}") %>">
      <%= market_place_type.name&.titleize %>
    </a>
  <% end %>
</div>

app/views/shared/_mobile_registration_form.html.erb
<div class="mobile-registration">
  <div class="mobile-sign-up-form">
    <div class="overlay">
      <div class="container text-center">
        <div class="mobile-reg-form">
          <div class="register text-center">
            <strong>Register Now</strong>
            <div class="reg_underline text-center">
              <%= image_tag 'white_reg_line.svg' %>
            </div>
          </div>
          <p class="note">These information will not be displayed to other users</p>
          <div class="bk-input-feilds">
            <%= form_for @user, url: user_registration_path do |f| %>

              <div class="<%= f.object.errors[:name].present? ? '' : 'form-group' %>">
                <%= f.text_field :name,
                                 autofocus: true,
                                 autocomplete: "full_name",
                                 required: true,
                                 class: 'form-control sign_up-input-field',
                                 placeholder: 'Full Name*'
                %>
                <small class="text-danger error-text">
                  <%= f.object.errors[:name].present? ? "Name #{f.object.errors[:name]&.first}" : '' %>
                </small>
              </div>

              <div class="<%= f.object.errors[:email].present? ? '' : 'form-group' %>">
                <%= f.email_field :email,
                                  autofocus: true,
                                  autocomplete: "email",
                                  class: 'form-control sign_up-input-field',
                                  placeholder: 'Email*' %>
                <small class="text-danger error-text">
                  <%= f.object.errors[:email].present? ? "Email #{f.object.errors[:email]&.first}" : '' %>
                </small>
              </div>

              <div class="<%= f.object.errors[:phone_number].present? ? '' : 'form-group' %>">
                <%= f.phone_field :phone_number,
                                  autofocus: true,
                                  autocomplete: "phone_number",
                                  required: true, class: 'form-control sign_up-input-field',
                                  placeholder: 'Mobile* (+8801XXXXXXXXX)' %>
                <small class="text-danger error-text">
                  <%= f.object.errors[:phone_number].present? ? "Mobile #{f.object.errors[:phone_number]&.first}" : '' %>
                </small>
              </div>

              <div class="<%= f.object.errors[:password].present? ? '' : 'form-group' %>">
                <%= f.password_field :password,
                                     autocomplete: "password",
                                     class: 'form-control sign_up-input-field',
                                     placeholder: 'Password*( Must be at least 6 characters )',
                                     minlength: '6',
                                     maxlength: '20',
                                     pattern: "(?=.*[a-z])(?=.*[A-Z]).{6,}",
                                     title: "Must have at least 6 characters including 1 uppercase and lowercase letter,
                                      1 number, 1 special character.",
                                     data: {toggle: 'tooltip', placement: 'top'},
                                     required: true %>
                <small class="text-danger error-text">
                  <%= f.object.errors[:password].present? ? "Password #{f.object.errors[:password]&.first}" : '' %>
                </small>
              </div>
              <div class="<%= f.object.errors[:password_confirmation].present? ? '' : 'form-group' %>">
                <%= f.password_field :password_confirmation,
                                     autocomplete: "new-password",
                                     class: 'form-control sign_up-input-field',
                                     required: true, placeholder: 'Confirm Password*' %>
                <small class="text-danger error-text">
                  <%= f.object.errors[:password_confirmation].present? ? "Confirm Password #{f.object.errors[:password_confirmation]&.first}" : '' %>
                </small>
              </div>

              <div class="<%= f.object.errors[:created_for].present? ? '' : 'form-group' %>">
                <%= f.select :created_for,
                             options_for_select(User::created_fors.to_h
                                                    .map {
                                                        |k, v| [k.titleize, k]
                                                    }),
                             {prompt: 'Created For*'},
                             required: true,
                             class: 'form-control sign_up-input-field' %>
                <small class="text-danger error-text">
                  <%= f.object.errors[:created_for].present? ? "Confirm Password #{f.object.errors[:created_for]&.first}" : '' %>
                </small>
              </div>

              <!--              <div class="notice pb-2">-->
              <!--                <span> (These information will <b>never</b> be disclosed through this platform) </span>-->
              <!--              </div>-->

              <div class="form-group form-check terms_and_condition">
                <label class="form-check-label">
                  <input class="form-check-input" type="checkbox" required> Have you read the
                  <a href="<%= terms_of_uses_path %>" target="_blank"> Terms of Use </a> &
                  <a href="<%= privacy_policies_path %>" target="_blank"> Privacy Policy </a> of Bolo Kobul?
                </label>
              </div>

              <div class="register-btn-section text-center merriweather">
                <button type="submit" class="btn btn-sign_up form-control">Register Free</button>
              </div>

            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/shared/_mobile_side_panel.html.erb
<div id="mySidebar" class="sidebar">
  <div class="site-bar-header pb-4">
    <a href="javascript:void(0)" class="site-panel-logo">
      <%= image_tag 'bk_logo.webp', width: '64', height: '64' %>
    </a>

    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>

    <% if current_user.present? %>
      <div class="mobile-site-bar-menu">
        <a href="<%=
          (current_user.marriage_profiles.present? && current_active_profile.present?) ?
              dashboard_marriage_profile_path(current_active_profile) : '#' %>"
           class="bk-active">
          <div class="">
            <i class="fa fa-tachometer"></i>
            <span class="pl-1">Dashboard</span>
          </div>
        </a>
        <a href="<%=
          current_active_profile.present? ?
              profile_info_marriage_profile_path(current_active_profile) : '#' %>"
           class="bk-active">
          <div class="">
            <i class="fa fa-user"></i>
            <span class="pl-1">Profile</span>
          </div>
        </a>
        <a href="<%=
          current_active_profile.present? ?
              orders_path : '#' %>"
           class="bk-active">
          <div class="">
            <i class="fa fa-cart-arrow-down" aria-hidden="true"></i>
            <span class="pl-1">Orders</span>
          </div>
        </a>
        <a href="<%=
          current_active_profile&.partner_preference.present? ?
              partner_preference_path(current_active_profile.partner_preference)
              : new_partner_preference_path %>"
           class="bk-active">
          <div class="">
            <i class="fas fa-user-shield"></i>
            <span class="pl-1">Preference</span>
          </div>
        </a>
        <a href="<%= customer_supports_path  %>" class="bk-active">
          <div class="">
            <i class="fas fa-headset"></i>
            Reported Issues
          </div>
        </a>
        <a href="<%= privacy_settings_path  %>" class="bk-active">
          <div class="">
            <i class="fa fa-user-cog"></i>
             Privacy Settings
          </div>
        </a>
        <a href="<%=
          (current_user.present? && current_active_profile.present?) ?
              search_page_marriage_profile_path(current_active_profile) : '#' %>"
           class="bk-active">
          <div class="">
            <i class="far fa-address-card"></i>
            <span class="pl-1">Search</span>
          </div>
        </a>
        <a href="<%= how_it_works_path %>" class="bk-active">
          <div class="">
            <i class="fas fa-cogs"></i>
            How It Works
          </div>
        </a>
        <a href="<%= market_places_path %>" class="bk-active">
          <div class="">
            <i class="fas fa-store"></i>
            Wedding Shopping
          </div>
        </a>
        <div class="dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="menu-title">
              <i class="fas fa-hands-helping"></i>
              Assisted Services
            </div>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <% AssistedService.order(:display_order).each do |assisted_service| %>
              <a class="dropdown-item" href="<%= assisted_service_path(assisted_service) %>">
                <%= assisted_service.name&.titleize %>
              </a>
            <% end %>
          </div>
        </div>
        <a href="<%= precautionary_measures_path %>" class="bk-active">
          <div class="">
            <i class="fas fa-exclamation-circle"></i>
            Precautionary Measures
          </div>
        </a>
        <a href="<%= notifications_users_path %>" class="bk-active notification-section">
          <div class="">
            <i class="fas fa-hand-holding-heart"></i>
            Notifications
            <span class="notification-counter">
              <%= current_user&.notifications&.unread&.count&.zero? ?
                      '' : current_user&.notifications&.unread&.count
              %>
          </span>
          </div>
        </a>
        <% unless current_user.self? || current_user.other_as_matchmaker? %>
          <div class="nav-item dropup text-center">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Switch Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <% if current_user.marriage_profiles.present? %>
                <% current_user&.marriage_profiles&.each do |profile| %>
                  <a class="dropdown-item" href="<%=
                    profile.persisted? ? switch_marriage_profile_path(profile)
                        : '#' %>">
                    <%= profile&.name || profile&.unique_id %> </a>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

    <% else %>
      <div class="mobile-site-bar-menu">
        <a class="bk-active" href="<%= about_path %>">
          <div class="">
            <i class="fas fa-hand-holding-heart"></i>
            About Us
          </div>
        </a>

        <a href="<%= how_it_works_path %>" class="bk-active">
          <div class="">
            <i class="fas fa-cogs"></i>
            How It Works
          </div>
        </a>

        <a href="<%= faqs_path %>" class="bk-active">
          <div class="">
            <i class="far fa-question-circle"></i>
            <span class="pl-1">FAQ</span>
          </div>
        </a>

        <a href="<%= precautionary_measures_path %>" class="bk-active">
          <div class="">
            <i class="fas fa-exclamation-circle"></i>
            <span class="pl-1">Precautionary Measures</span>
          </div>
        </a>

        <a href="<%= blogs_path type: "success_story" %>" class="bk-active">
          <div class="">
            <i class="fas fa-hand-holding-heart"></i>
            Success Stories
          </div>
        </a>

        <a href="<%= blogs_path %>" class="bk-active">
          <div class="">
            <i class="far fa-newspaper"></i>
            Blogs
          </div>
        </a>

        <a href="<%= market_places_path %>" class="bk-active">
          <div class="">
            <i class="fas fa-store"></i>
            Wedding Shopping
          </div>
        </a>

        <div class="dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="menu-title">
              <i class="fas fa-hands-helping"></i>
              Assisted Services
            </div>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <% AssistedService.order(:display_order).each do |assisted_service| %>
              <a class="dropdown-item" href="<%= assisted_service_path(assisted_service) %>">
                <%= assisted_service.name&.titleize %>
              </a>
            <% end %>
          </div>
        </div>

        <a href="<%= contact_path %>" class="bk-active">
          <div class="">
            <i class="far fa-address-card"></i>
            Contact Us
          </div>
        </a>
      </div>
    <% end %>
  </div>

  <div class="site-bar-footer text-white">
    <div class="pt-2 social-link">
      <%= render 'shared/social_media_link', text_color:'text-white' %>
    </div>

  </div>

</div>

<script>
    function openNav() {
        document.getElementById("mySidebar").style.width = "265px";
        $("body").css("overflow", "hidden");
    }

    function closeNav() {
        document.getElementById("mySidebar").style.width = "0";
        $("body").css("overflow", "visible");
    }
</script>

app/views/shared/_modal.html.erb
<!-- Login Modal -->
<div class="modal fade" id="loginModal">
  <div class="modal-dialog modal-sm modal-dialog-centered">
    <div class="modal-content">

      <!-- Modal body -->
      <div class="modal-body">
        <div class="d-sm-flex flex-sm-column pb-3">
          <button type="button" class="close bk-modal-close" data-dismiss="modal">&times;</button>
          <%= render 'home/sign_in_form' %>
        </div>
      </div>

    </div>
  </div>
</div>

<!-- The update form modal -->
<div class="modal" id="global_update_modal_sm">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/shared/_modal_header.html.erb
<div class="modal-header ">
  <h4 class="modal-title"> <%= title %></h4>
  <div class="error-modal-notice"></div>
  <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>

app/views/shared/_profile_photo.html.erb
<%= link_to profile_info_marriage_profile_path(profile) do %>
  <%= image_tag profile.profile_image.present? ?
                    profile.profile_image.url(:profile_thumb) : 'bk-upload-photo.png',
                width: '74', height:'74',
                class: 'img-thumbnail rounded-circle' %>
<% end %>