config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Only allow authenticated users to get access
  # to the Sidekiq web interface
  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#landing'
  get '/email_template', to: 'home#email_template', as: 'email_template'
  get '/about', to: 'home#about', as: 'about'
  get '/contact', to: 'home#contact', as: 'contact'
  get '/animation', to: 'home#animation'
  get '/use_reference', to: 'home#use_reference', as: 'reference'

  resources :messages do
    member do
      get :profile
    end
  end

  resources :users, shallow: true do
    collection do
      get :notifications
      post :mark_notification_read
      patch :update_referral_code
    end
    member do
      get :show_verify
      post :verify
      post :resend
      get :change_password
      patch :update_password
      patch :deactivate_account
      patch :activate_account
      patch :toggle_text_alert
      patch :toggle_advanced_search
    end
  end

  resources :orders, except: %i[edit update destroy] do
    member do
      post :success
      post :fail
      post :cancel
    end
  end

  resources :partner_preferences do
  end

  resources :marriage_profiles do
    collection do
      get :blocked_profiles
      get :pending_profiles
      get :requested_profiles
      get :refferel_code
    end
    member do
      get :profile_info
      get :dashboard
      get :switch
      get :edit_about
      patch :update_about
      post :send_request
      patch :accept_request
      patch :reject_request
      patch :cancel_request
      patch :remove_profile
      patch :block_profile
      patch :unblock_profile
      patch :change_profile
      patch :change_photo
      get :requested_profiles
      get :search_page
      get :search
      post :search
    end
  end

  resources :advertiser_profiles
  resources :occupations
  resources :appearances
  resources :family_members
  resources :marriage_informations
  resources :life_styles
  resources :hobbies_and_interests
  resources :cultural_values
  resources :academic_informations
  resources :favourites do
    collection do
      delete :remove
    end
  end

  resources :blogs
  resources :market_places
  resources :terms_of_uses
  resources :privacy_policies
  resources :faqs
  resources :assisted_services
  resources :precautionary_measures
  resources :process_flows, as: :how_it_works, path: :how_it_works
  resources :customer_supports
  resources :privacy_settings do
    member do
      put :toggle_update
    end
  end
  resources :chat_friendships do
    member do
      post :send_request
      patch :accept_request
      patch :reject_request
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, 
  :check_current_active_profile, 
  :check_preference, except: [:landing, :about, :email_template, :contact, :animation]

  def landing
    @user = User.new
    @success_stories = Blog.approved.success_story
  end

  def about
    @about_content = About.all.order(:display_order)
  end

  def contact
    @contact = Contact.last
  end

  def email_template

  end

  def animation
  end

  def use_reference
    @user = current_user
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_sign_in_form.html.erb
<%= form_for("user", :url => user_session_path) do |f| %>
<div class="bk-login-form">

  <div class="text-center">
    <%= image_tag 'bk_logo.webp', width: '85', height: '85' %>
    <div class="text-center pb-4">
     <span class="text-gray"> Don't wait for love to find you. </span> <br>
      <strong> Login Now! </strong>
    </div>
  </div>

  <div class="form-group">
    <%= f.text_field :login,
                     type: 'phone',
                     class: 'form-control',
                     placeholder: 'Email / Mobile (+8801xxxxxxxx)',
                     required: true  %>
  </div>

  <div class="form-group">
    <%= f.text_field :password, type: 'password',
                     class: 'form-control',
                     placeholder: 'Password', required: true %>
  </div>

  <div class="d-flex flex-row remember-password">
    <div class="checkbox flex-fill">
      <label class="bk-check-box">
        <%= f.check_box :remember_me %>
        <span class=""> Remember me </span>
      </label>
    </div>


    <div class="forget-password">
      <%= link_to 'Forgot Password?', new_user_password_path, class: ''%>
    </div>
  </div>


  <div class="bk-login-btn">
    <%= f.submit 'LOGIN', class: 'form-control btn btn-warning text-white' %>
  </div>

</div>

<% end %>

app/views/home/_sign_up_form.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>
  <div class="wrap-input100 m-b-10 validate-input" data-validate = "Name is required">
    <%= f.text_field :name,
                     class: 's2-txt1 placeholder0 input100',
                     placeholder: 'Full Name' %>
    <span class="focus-input100"></span>
  </div>

  <div class="wrap-input100 m-b-20 validate-input" data-validate = "Email is required: ex@abc.xyz">
    <%= f.text_field :email,
                     type: 'Email',
                     class: 's2-txt1 placeholder0 input100',
                     placeholder: 'Email Address'%>
    <span class="focus-input100"></span>
  </div>

  <div class="wrap-input100 m-b-20 validate-input" data-validate = "Email is required: ex@abc.xyz">
    <%= f.text_field :phone_number,
                     type: 'phone',
                     class: 's2-txt1 placeholder0 input100',
                     placeholder: 'Mobile Number' %>
    <span class="focus-input100"></span>
  </div>

  <div class="wrap-input100 m-b-20 validate-input" data-validate = "Email is required: ex@abc.xyz">
    <%= f.text_field :password, type: 'password',
                     class: 's2-txt1 placeholder0 input100',
                     placeholder: 'Password', required: true %>
    <span class="focus-input100"></span>
  </div>

  <div class="wrap-input100 m-b-20 validate-input" data-validate = "Email is required: ex@abc.xyz">
    <%= f.text_field :password_confirmation, type: 'password',
                     class: 's2-txt1 placeholder0 input100',
                     placeholder: 'Reconfirm Password', required: true %>
    <span class="focus-input100"></span>
  </div>
<!--  <p class="sm-text">(These information will <b>never</b> be disclosed to anyone through the platform)</p>-->
  <div class="w-full">
    <%= f.submit 'REGISTER FREE', class: 'flex-c-m s2-txt2 size4 bg6 bor1 hov1 trans-04 merriweather' %>
  </div>

<% end %>

app/views/home/about.html.erb
<div class="container blogs-container">
  <h2 class="blogs-header">
    About Us
  </h2>
  <hr class="section-hr mt-0 mb-0">
  <div class="blogs-items">
    <div class="col-md-12 p-0 float-left">
      <div class="row">
        <div class="blogs-content col-md-9 mb-4">
          <%= render 'shared/about_content', about_content: @about_content %>
        </div>
        <div class="col-md-3 p-0 float-right pt-2">
          <%= render partial: 'shared/ad_for_about_page' %>
        </div>
      </div>
    </div>
  </div>

  <!-- campaign section -->
    <%= render 'home/landing/campaign' unless user_signed_in? %>
</div>

app/views/home/animation.html.erb
<div class="bird-container bird-container--one">
		<div class="bird bird--one"></div>
</div>

app/views/home/contact.html.erb
<div class="container blogs-container">
  <h2 class="blogs-header">
    Contact Us
  </h2>
  <hr class="section-hr mt-0 mb-0">
  <div class="blogs-items">
    <div class="col-md-12 p-0 float-left">
      <div class="row">
        <div class="blogs-content col-md-9">
          <%= render 'shared/contact_content', contact: @contact %>
        </div>
        <div class="col-md-3 p-0">
          <%= render partial: 'shared/ad_for_about_page' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/email_template.html.erb
<b> Dear Concern, </b>
<p> Your first step to finding your life partner is complete! </p>

<p> Welcome to <a href="http://www.bolokobul.com"></a>bolokobul.com, the first of a kind one- stop platform for finding your soul mate. Bolo Kobul lets you browse through our verified databse based on your preference, while ensuring your data is completely secured. </p>

<p> To ensure seamless service, our website is currently being developed with care. We will soon share with you the rest of the steps of registration. </p>

<p> Thank you for your patience! </p>

<p> Best wishes </p>
<p> Team BK </p>

app/views/home/landing.html.erb
<!--slider section-->
<%= render 'home/landing/slider' %>

<!--Features section-->
<%= render 'home/landing/feature_packages' %>

<!-- success story-->
<%= render 'home/landing/success_stories' %>

<!-- campaign section -->
<%= render 'home/landing/campaign' %>

<!-- weeding business section-->
<%= render 'home/landing/weeding_business' %>

app/views/home/use_reference.html.erb
<div class="container blogs-container">
  <h2 class="blogs-header">
    Reference Promo Code
  </h2>
  <hr class="section-hr mt-0 mb-0">
  <div class="blogs-items">
    <div class="col-md-12 p-0 float-left">
      <div class="row">
        <div class="blogs-content col-md-9">
          <% if @user.refferel_promo_code.present? %>
            <div class="no-data-found alert text-center text-gray">
              <p> You are not eligible to use any more referral promo code. You have already used a referral code. </p>
            </div>
          <% else %>
            <%= form_for @user, url: update_referral_code_users_path, method: :patch do |f| %>
              <div class="modal-body">
                <div class="form_input_fields pl-2 pr-2">
                  <div class="form-group">
                    <%= f.text_field :refferel_promo_code,
                                     autofocus: true,
                                     autocomplete: "refferel_promo_code",
                                     class: 'form-control sign_up-input-field',
                                     placeholder: 'Type referral code',
                                     title: 'Referral code ',
                                     data: {toggle: 'tooltip', placement: 'top'},
                                     required: true %>
                  </div>
                  <%= f.submit 'Submit', class: 'btn btn-warning text-white btn-sm' %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
        <div class="col-md-3 p-0">
          <%= render partial: 'shared/ad_for_about_page' %>
        </div>
      </div>
    </div>
  </div>

</div>