config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Only allow authenticated users to get access
  # to the Sidekiq web interface
  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#landing'
  get '/email_template', to: 'home#email_template', as: 'email_template'
  get '/about', to: 'home#about', as: 'about'
  get '/contact', to: 'home#contact', as: 'contact'
  get '/animation', to: 'home#animation'
  get '/use_reference', to: 'home#use_reference', as: 'reference'

  resources :messages do
    member do
      get :profile
    end
  end

  resources :users, shallow: true do
    collection do
      get :notifications
      post :mark_notification_read
      patch :update_referral_code
    end
    member do
      get :show_verify
      post :verify
      post :resend
      get :change_password
      patch :update_password
      patch :deactivate_account
      patch :activate_account
      patch :toggle_text_alert
      patch :toggle_advanced_search
    end
  end

  resources :orders, except: %i[edit update destroy] do
    member do
      post :success
      post :fail
      post :cancel
    end
  end

  resources :partner_preferences do
  end

  resources :marriage_profiles do
    collection do
      get :blocked_profiles
      get :pending_profiles
      get :requested_profiles
      get :refferel_code
    end
    member do
      get :profile_info
      get :dashboard
      get :switch
      get :edit_about
      patch :update_about
      post :send_request
      patch :accept_request
      patch :reject_request
      patch :cancel_request
      patch :remove_profile
      patch :block_profile
      patch :unblock_profile
      patch :change_profile
      patch :change_photo
      get :requested_profiles
      get :search_page
      get :search
      post :search
    end
  end

  resources :advertiser_profiles
  resources :occupations
  resources :appearances
  resources :family_members
  resources :marriage_informations
  resources :life_styles
  resources :hobbies_and_interests
  resources :cultural_values
  resources :academic_informations
  resources :favourites do
    collection do
      delete :remove
    end
  end

  resources :blogs
  resources :market_places
  resources :terms_of_uses
  resources :privacy_policies
  resources :faqs
  resources :assisted_services
  resources :precautionary_measures
  resources :process_flows, as: :how_it_works, path: :how_it_works
  resources :customer_supports
  resources :privacy_settings do
    member do
      put :toggle_update
    end
  end
  resources :chat_friendships do
    member do
      post :send_request
      patch :accept_request
      patch :reject_request
    end
  end
end

app/models/academic_information.rb
# == Schema Information
#
# Table name: academic_informations
#
#  id                  :bigint           not null, primary key
#  degree              :string
#  end_date            :datetime
#  institution         :string
#  passing_year        :string
#  result              :integer
#  start_date          :datetime
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  marriage_profile_id :integer
#

# TODO: why passing_year is integer field?
class AcademicInformation < ApplicationRecord

  #
  # enum, constant & attr
  #



  #
  # Associations
  #

  belongs_to :marriage_profile

  #
  # callbacks
  #

  after_create :profile_progress_recalculate
  after_destroy :profile_progress_recalculate

  private

  def profile_progress_recalculate
    marriage_profile.progress_recalculate
  end
end

app/controllers/academic_informations_controller.rb
class AcademicInformationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_academic_info, only: [:edit, :update, :destroy]

  def new
    @academic_info = AcademicInformation.new
  end

  def create
    respond_to do |format|
      @academic_info = current_active_profile.academic_informations.build(academic_info_params)
      if @academic_info.save
        format.js { flash[:notice] = "Academic information added successfully." }
      else
        format.js { flash[:notice] = "Academic information failed to update. Try again" }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @academic_info.update(academic_info_params)
        format.js { flash[:notice] = "Academic information updated successfully." }
      else
        format.js { flash[:notice] = "Academic information failed to update. Try again" }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @academic_info.destroy
        format.js { flash[:notice] = "Academic information deleted successfully." }
      else
        format.js { flash[:notice] = "Academic information failed to delete. Try again" }
      end
    end
  end

  private

  def set_academic_info
    @academic_info = AcademicInformation.find_by(id: params[:id])
  end

  def academic_info_params
    params.require(:academic_information).permit!
  end
end

app/helpers/academic_informations_helper.rb
module AcademicInformationsHelper
end

app/views/academic_informations/_academic_form.html.erb
<%= form_for academic_info, remote:true do |f| %>
  <!-- Modal Header -->
  <%= render 'shared/modal_header', title: "#{academic_info.new_record? ? 'Add Academic Information' : 'Edit Academic Information'}" %>

  <!-- Modal body -->
  <div class="modal-body">
    <div class="form_input_fields pl-2 pr-2">

      <div class="form-group">
        <%= f.text_field :degree, class: 'form-control sign_up-input-field', placeholder:'Degree', data: {toggle: 'tooltip', placement: 'top'}, title: 'Degree' %>
      </div>

      <div class="form-group">
        <%= f.text_field :institution, class: 'form-control sign_up-input-field', placeholder:'Institution', data: {toggle: 'tooltip', placement: 'top'}, title: 'Institution' %>
      </div>

      <div class="form-group">
        <%= f.number_field :passing_year, min: 1900,
                           max: Date.today.year + 5,
                           class: 'form-control sign_up-input-field',
                           placeholder:'Passing Year',
                           data: {toggle: 'tooltip', placement: 'top'},
                           title: 'Passing Year' %>
      </div>
    </div>
  </div>

  <!-- Modal footer -->
  <%= render 'shared/modal_footer', f: f %>
<% end %>

app/views/academic_informations/_academic_info.html.erb
<div class="panel-group">
  <div class="panel p-2 default-background white-background">
    <div class="info-yellow-line"></div>
    <div class="panel-heading">
      <div class="d-flex flex-row">
        <div class=" flex-fill pl-2 pt-1">
          <strong class=""> Academic information </strong>
        </div>
        <div class="align-self-end pr-2">
          <a data-toggle="collapse" href="#collapse_academic_info" class="align-self-end text-white">
            <i class="fas fa-caret-down"></i>
          </a>
        </div>
      </div>
    </div>
    <% %>
    <div id="collapse_academic_info" class="panel-collapse collapse p-2 detail-info">
      <% if marriage_profile.id == current_active_profile.id %>
        <div class="pr-2 new-info-btn">
          <a href="<%= new_academic_information_path %>" data-remote="true" data-toggle="tooltip" data-placement="top" title="New Academic Information" class="btn btn-sm btn-edit text-white">
            <i class="fa fa-plus-circle"></i>
          </a>
        </div>
      <% end %>
      <% if marriage_profile.academic_informations.present? %>
        <% marriage_profile.academic_informations&.order(passing_year: :DESC)&.each do |academic_info| %>
          <div class="detail-info ">
            <% if marriage_profile.id == current_active_profile.id %>
              <div class="edit-info-btn">
                <a href="<%= edit_academic_information_path(academic_info) %>" data-remote="true" data-toggle="tooltip" data-placement="top" title="Edit information" class="btn btn-sm btn-edit text-white">
                  <i class="fa fa-pencil"></i>
                </a>
              </div>
              <div class="delete-info-btn">
                <a href="<%= academic_information_path(academic_info) %>" data-method="delete" data-remote="true"
                   data-toggle="tooltip" data-placement="top" title="Remove information" class="btn btn-sm btn-delete text-white"
                   data-confirm="Are you confirm?">
                  <i class="fa fa-trash-alt"></i>
                </a>
              </div>
            <% end %>
            <div class="panel-body border-top">
              <div class="d-sm-flex flex-sm-row info-alignment">
                <table class=" flex-fill pr-3 table table-borderless table-responsive ">
                  <tbody>
                  <tr>
                    <td> Institution</td>
                    <td>:</td>
                    <td><%= academic_info.institution.present? ? academic_info.institution : '' %></td>
                  </tr>

                  <tr>
                    <td> Degree</td>
                    <td>:</td>
                    <td><%= academic_info.degree.present? ? academic_info.degree : '' %></td>
                  </tr>
                  <% if marriage_profile.id == current_active_profile.id || current_active_profile.chat_view?(marriage_profile) %>
                    <tr>
                      <td> Passing Year</td>
                      <td>:</td>
                      <td><%= academic_info.passing_year.present? ? academic_info.passing_year : '' %> </td>
                    </tr>
                  <% end %>

                  </tbody>
                </table>
                <table class=" flex-fill pr-3 table table-borderless table-responsive ">
                  <tbody>
                  <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                  </tr>

                  </tbody>
                </table>
              </div>

            </div>
          </div>
        <% end %>
      <% else %>
        <%= render 'shared/no_data_found' %>
      <% end %>
    </div>
  </div>
</div>

app/views/academic_informations/create.js.erb
$('.academic_info').html("<%= escape_javascript(render 'academic_informations/academic_info', marriage_profile: @academic_info.marriage_profile ) %>");
$('#global_update_modal_sm').modal('hide');
$(".update-notice").html('<%= j render partial: "shared/flash_message", locals: { notice: flash[:notice] } %>');

app/views/academic_informations/destroy.js.erb
$('.academic_info').html("<%= escape_javascript(render 'academic_informations/academic_info', marriage_profile: @academic_info.marriage_profile ) %>");
$(".update-notice").html('<%= j render partial: "shared/flash_message", locals: { notice: flash[:notice] } %>');

app/views/academic_informations/edit.js.erb
$('#global_update_modal_sm').modal({backdrop:'static', keyboard:false, show: true}).find('.modal-content').html("<%= escape_javascript(render 'academic_form', academic_info: @academic_info) %>");

app/views/academic_informations/new.js.erb
$('#global_update_modal_sm').modal({backdrop:'static', keyboard:false, show: true}).find('.modal-content').html("<%= escape_javascript(render 'academic_form', academic_info: @academic_info) %>");

app/views/academic_informations/update.js.erb
$('.academic_info').html("<%= escape_javascript(render 'academic_informations/academic_info', marriage_profile: @academic_info.marriage_profile ) %>");
$('#global_update_modal_sm').modal('hide');
$(".update-notice").html('<%= j render partial: "shared/flash_message", locals: { notice: flash[:notice] } %>');