config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Only allow authenticated users to get access
  # to the Sidekiq web interface
  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#landing'
  get '/email_template', to: 'home#email_template', as: 'email_template'
  get '/about', to: 'home#about', as: 'about'
  get '/contact', to: 'home#contact', as: 'contact'
  get '/animation', to: 'home#animation'
  get '/use_reference', to: 'home#use_reference', as: 'reference'

  resources :messages do
    member do
      get :profile
    end
  end

  resources :users, shallow: true do
    collection do
      get :notifications
      post :mark_notification_read
      patch :update_referral_code
    end
    member do
      get :show_verify
      post :verify
      post :resend
      get :change_password
      patch :update_password
      patch :deactivate_account
      patch :activate_account
      patch :toggle_text_alert
      patch :toggle_advanced_search
    end
  end

  resources :orders, except: %i[edit update destroy] do
    member do
      post :success
      post :fail
      post :cancel
    end
  end

  resources :partner_preferences do
  end

  resources :marriage_profiles do
    collection do
      get :blocked_profiles
      get :pending_profiles
      get :requested_profiles
      get :refferel_code
    end
    member do
      get :profile_info
      get :dashboard
      get :switch
      get :edit_about
      patch :update_about
      post :send_request
      patch :accept_request
      patch :reject_request
      patch :cancel_request
      patch :remove_profile
      patch :block_profile
      patch :unblock_profile
      patch :change_profile
      patch :change_photo
      get :requested_profiles
      get :search_page
      get :search
      post :search
    end
  end

  resources :advertiser_profiles
  resources :occupations
  resources :appearances
  resources :family_members
  resources :marriage_informations
  resources :life_styles
  resources :hobbies_and_interests
  resources :cultural_values
  resources :academic_informations
  resources :favourites do
    collection do
      delete :remove
    end
  end

  resources :blogs
  resources :market_places
  resources :terms_of_uses
  resources :privacy_policies
  resources :faqs
  resources :assisted_services
  resources :precautionary_measures
  resources :process_flows, as: :how_it_works, path: :how_it_works
  resources :customer_supports
  resources :privacy_settings do
    member do
      put :toggle_update
    end
  end
  resources :chat_friendships do
    member do
      post :send_request
      patch :accept_request
      patch :reject_request
    end
  end
end

app/controllers/marriage_profiles_controller.rb
class MarriageProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_marriage_profile, only: [:edit_about, :update_about, :edit,
                                              :update, :profile_info, :show,
                                              :change_profile, :change_photo,
                                              :send_request, :accept_request,
                                              :cancel_request, :reject_request,
                                              :block_profile, :remove_profile,
                                              :unblock_profile, :switch,
                                              :dashboard, :search_page, :search]
  before_action :check_current_active_profile, :check_preference, except: [:new, :create]

  def index
    @marriage_profile = MarriageProfile.new
    render 'new'
  end

  def show
    render :profile_info
  end

  def dashboard
  end

  def profile_info
  end

  def switch
    session[:marriage_profile_id] = @marriage_profile.id if @marriage_profile.present?
    redirect_to profile_info_marriage_profile_path(@marriage_profile)
  end

  def search_page
    @matches = SearchService.with_params(params, @marriage_profile.id)
  end

  def search
    @matches = SearchService.with_params(params, @marriage_profile.id)
  end

  def new
    @marriage_profile_count = current_user.marriage_profiles.count
    @max_marriage_profiles = ButterflyConfig.last.present? ?
                              ButterflyConfig.last.max_marriage_profiles : 5
    if @marriage_profile_count >= @max_marriage_profiles
      redirect_back fallback_location: root_path,
                    notice: 'You have already reached the maximum number of
                            profiles one can create for others!'
    else
      @marriage_profile = MarriageProfile.new
    end
  end

  def create
    @marriage_profile = current_user.marriage_profiles.build(marriage_profile_params)
    if @marriage_profile.save
      session[:marriage_profile_id] = @marriage_profile.id
      redirect_to new_partner_preference_path
    else
      render 'new'
    end
  end

  def edit_about
  end

  def update
    respond_to do |format|
      if @marriage_profile.update(marriage_profile_params)
        format.js { flash[:notice] = "Basic information updated successfully." }
      else
        format.js { flash[:notice] = "#{@marriage_profile.errors.full_messages.first}" }
      end
    end
  end

  def change_profile
    respond_to do |format|
      if @marriage_profile.update(marriage_profile_params)
        format.js { flash[:notice] = "Successfully uploaded your profile picture!" }
      else
        format.js { flash[:notice] = "#{@marriage_profile.errors.full_messages.first}" }
      end
    end
  end

  def change_photo
    respond_to do |format|
      if @marriage_profile != current_active_profile
        format.js { flash[:notice] = "Permission denied!" }
      elsif @marriage_profile.update(params.require(:marriage_profile).permit(:photo_1, :photo_2, :photo_3, :profile_image))
        format.js { flash[:notice] = "Successfully uploaded your profile picture!" }
      else
        format.js { flash[:notice] = "#{@marriage_profile.errors.full_messages.first}" }
      end
    end
  end

  # def change_profile
  #   respond_to do |format|
  #     if params[:profile_image].present?
  #       @marriage_profile.update(profile_image: params[:profile_image], crop_x: params[:crop_x], crop_y: params[:crop_y], crop_w: params[:crop_w], crop_h: params[:crop_h])
  #       p 'controller'
  #       p @marriage_profile.crop_x
  #       format.js { flash[:notice] = "Successfully uploaded your profile picture!" }
  #     else
  #       format.js { flash[:notice] = "#{@marriage_profile.errors.full_messages.first}" }
  #     end
  #     # @marriage_profile = current_active_profile
  #     # format.js
  #     # format.html
  #   end
  # end

  def update_about
    respond_to do |format|
      if @marriage_profile.update(marriage_profile_params)
        format.js { flash[:notice] = "About yourself updated successfully." }
      else
        format.js { flash[:error] = "#{@marriage_profile.errors.full_messages.first}" }
      end
    end
  end

  def edit
  end

  def send_request

    if current_active_profile.friend_ids.include? @marriage_profile.id
      flash[:notice] = "You are already in friends with each other!"
      redirect_back(fallback_location: "/") && return
    end

    if current_active_profile.has_bfly_for_profile_view?
      sending_request = current_active_profile.friend_request(@marriage_profile)
      if sending_request.present?
        current_active_profile.block_butterflies
        current_user.notifications.create(
          content: "Your butterfly has been sent successfully",
          notifiable: @marriage_profile,
          will_email: false,
          will_sms: false
        )
        KobulOneMailer.with(user: current_user, profile: @marriage_profile).send_request.deliver_later
        SmsService.call(
          current_user.phone_number.to_s,
          "Your butterfly has been sent successfully! Visit: www.bolokobul.com"
        )

        @marriage_profile.user.notifications.create(
          content: "A butterfly has fluttered your way! Check out the profile who has shown interest",
          notifiable: @marriage_profile,
          will_email: false,
          will_sms: false
        )
        KobulOneMailer.with(user: @marriage_profile.user).receive_request.deliver_later
        SmsService.call(
          @marriage_profile.user.phone_number.to_s,
          "Someone wants to know you better! To know your prospect, check #{profile_dashboard_url(@marriage_profile)}"
        )
      end
      if current_active_profile.favourite_profile_ids.include?(@marriage_profile.id)
        Favourite.remove_from_favourite(@marriage_profile.id)
      end
      flash[:notice] = "Your butterfly has been sent successfully"
      session[:butterfly] = "animate"
      redirect_back(fallback_location: "/")
    else
      flash[:danger] = "You don't have enough butterflies or they are in use!"
      redirect_to new_order_path
    end
  end

  def accept_request
    if current_active_profile.friend_ids.include? @marriage_profile.id
      flash[:notice] = "You are already in friends with each other!"
      redirect_back(fallback_location: "/") && return
    end

    if current_active_profile.has_bfly_for_profile_view?
      accept_request = current_active_profile.accept_request(@marriage_profile)
      if accept_request.present?
        current_active_profile.use_butterflies
        @marriage_profile.use_with_blocked_butterflies
        current_user.notifications.create(
          content: "Learn more about #{@marriage_profile.unique_id}. Send them a butterfly if you are interested to proceed",
          notifiable: @marriage_profile,
          will_email: false,
          will_sms: false
        )
        KobulOneMailer.with(user: current_user, profile: @marriage_profile).accept_request.deliver_later
        SmsService.call(
          current_user.phone_number.to_s,
          "Learn more about your potential prospect #{profile_dashboard_url(@marriage_profile)}"
        )

        @marriage_profile.user.notifications.create(
          content: "#{current_active_profile.unique_id} has accepted your butterfly! Check more details on their profile",
          notifiable: @marriage_profile,
          will_email: false,
          will_sms: false
        )
        KobulOneMailer.with(user: @marriage_profile.user, profile: current_active_profile).get_acceptance.deliver_later
        SmsService.call(
          @marriage_profile.user.phone_number.to_s,
          "The one you wanted to know more has responded. To know more about your potential prospect, visit #{profile_dashboard_url(@marriage_profile)}"
        )
      end
      flash[:notice] = "Request accepted successfully."
      redirect_to dashboard_marriage_profile_path(current_active_profile,
                                                  butterfly: "animate")
    else
      flash[:danger] = "You don't have enough butterflies or they are in use!"
      redirect_to new_order_path
    end
  end

  def reject_request
    cancel_request = current_active_profile.decline_request(@marriage_profile)
    if cancel_request.present?
      @marriage_profile.unblock_blocked_butterflies
      @marriage_profile.user.notifications.create(
        content: "#{current_active_profile.unique_id} did not accept your butterfly!",
        notifiable: @marriage_profile,
        will_email: false,
        will_sms: false
      )
      KobulOneMailer.with(user: @marriage_profile.user, profile: current_active_profile).get_rejection.deliver_later
      SmsService.call(
        @marriage_profile.user.phone_number.to_s,
        "A butterfly was not accepted. Find more profiles at www.bolokobul.com"
      )
    end
    flash[:notice] = "kobul (1) request cancelled"
    redirect_to dashboard_marriage_profile_path(current_active_profile)
  end

  def cancel_request
    cancel_request = current_active_profile.decline_request(@marriage_profile)
    if cancel_request.present?
      current_active_profile.unblock_blocked_butterflies
    end
    flash[:notice] = "kobul (1) request cancelled, you got your butterfly back!"
    redirect_to dashboard_marriage_profile_path(current_active_profile,
                                                butterfly: "bk_animate")
  end

  def remove_profile
    current_active_profile.remove_friend(@marriage_profile)
  end

  def block_profile
    current_active_profile.block_friend(@marriage_profile)
    flash[:notice] = "Blocked successfully."
    redirect_to dashboard_marriage_profile_path(current_active_profile)
  end

  def unblock_profile
    current_active_profile.unblock_friend(@marriage_profile)
    redirect_back fallback_location: root_path, notice: 'Unblocked successfully from your blocked list.'
  end

app/helpers/marriage_profiles_helper.rb
module MarriageProfilesHelper

  def get_recommended_profiles
    preference_level = 5
    recommended_profiles = []
    while recommended_profiles.count < 10 && preference_level > 0
      recommended_profiles += RecommendationService.with_preference(
        current_active_profile,
        preference_level,
        recommended_profiles.map(&:id)
      ).to_a
      preference_level -= 1
    end

    recommended_profiles = recommended_profiles.each { |profile| profile.calculate_matching_percentage! current_active_profile }
    recommended_profiles.sort_by{|profile| -profile.matching_percentage}
  end

  def get_accepted_profiles
    accepted_profiles = MarriageProfile.accepted_profiles(current_active_profile)
  end

  def get_requested_profiles
    requested_profiles = MarriageProfile.requested_profiles(current_active_profile)
  end

  def get_pending_profiles
    pending_profiles = current_active_profile.pending_friends
  end

  def chat_channels
    current_active_profile.chat_rooms
  end

end

app/views/marriage_profiles/_appearance.html.erb
<div class="d-sm-flex flex-sm-column pt-1">
  <div class="profile-info-item appearance_info">
    <%= render 'appearances/appearance_info', marriage_profile: marriage_profile %>
  </div>
</div>

app/views/marriage_profiles/_basic_info.html.erb
<div class="d-sm-flex flex-sm-column pt-1">
  <div class="basic_profile_info profile-info-item">
    <%= render 'basic_profile_info', marriage_profile: marriage_profile  %>
  </div>
</div>

app/views/marriage_profiles/_blocked_list.html.erb
<div class="right-section mb-4">
  <div class="d-flex flex-column dashboard-tab">
    <% if blocked_profiles.present? %>
      <% blocked_profiles.each do |profile| %>
        <div class="d-flex flex-row white-background text-gray p-3 border-bottom">
          <div class="col-12">
            <div class="row">
              <div class="col-4">
                <%= profile&.unique_id %>
              </div>
              <div class="col-4">
                <i class="fa fa-ban text-danger" title="Blocked" data-toggle="tooltip" data-placement="top"></i>
              </div>
              <div class="col-4">
                <%= link_to unblock_profile_marriage_profile_path(profile), method: :patch do %>
                  Unblock
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <%= render 'shared/no_data_found' %>
    <% end %>
  </div>

</div>

app/views/marriage_profiles/_family_details.html.erb
<div class="d-sm-flex flex-sm-column pt-1">
  <div class="family_details_info profile-info-item">
    <%= render 'family_members/family_details_info', marriage_profile: marriage_profile %>
  </div>
</div>

app/views/marriage_profiles/_marriage_information.html.erb
<div class="d-sm-flex flex-sm-column pt-1">
  <div class="marriage_info profile-info-item">
    <%= render 'marriage_informations/marriage_info', marriage_profile: marriage_profile %>
  </div>
</div>

app/views/marriage_profiles/_marriage_profile_information.html.erb
<div class="marriage_information pt-3">
  <div id="marriage_profile_photos">
    <%= render 'marriage_profiles/photos',
               marriage_profile: marriage_profile if current_active_profile.full_view?(marriage_profile) ||
      current_active_profile.chat_view?(marriage_profile) %>
  </div>

  <%= render 'marriage_profiles/basic_info',
             marriage_profile: marriage_profile if current_active_profile.full_view?(marriage_profile) ||
      current_active_profile.more_view?(marriage_profile) %>

  <%= render 'marriage_profiles/academic_information',
             marriage_profile: marriage_profile if current_active_profile.full_view?(marriage_profile) ||
      current_active_profile.more_view?(marriage_profile) %>

  <%= render 'marriage_profiles/occupation',
             marriage_profile: marriage_profile if current_active_profile.full_view?(marriage_profile) ||
      current_active_profile.more_view?(marriage_profile) %>

  <%= render 'marriage_profiles/appearance',
             marriage_profile: marriage_profile if current_active_profile.full_view?(marriage_profile) ||
      current_active_profile.more_view?(marriage_profile) %>

  <%= render 'marriage_profiles/family_details',
             marriage_profile: marriage_profile if current_active_profile.full_view?(marriage_profile) ||
      current_active_profile.chat_view?(marriage_profile)
  %>

  <%= render 'marriage_profiles/marriage_information',
             marriage_profile: marriage_profile if current_active_profile.full_view?(marriage_profile)  ||
      current_active_profile.more_view?(marriage_profile)
  %>

  <%= render 'marriage_profiles/life_style',
             marriage_profile: marriage_profile %>

  <%= render 'marriage_profiles/hobbies_and_interest',
             marriage_profile: marriage_profile %>

  <%= render 'marriage_profiles/cultural_values',
             marriage_profile: marriage_profile %>

  <%= render 'marriage_profiles/about_myself',
             marriage_profile: marriage_profile if current_active_profile.full_view?(marriage_profile) ||
      current_active_profile.more_view?(marriage_profile) %>

</div>

app/views/marriage_profiles/_refferel_code.html.erb
<div class="right-section mb-4">
  <div class="d-flex flex-column dashboard-tab">
    <div class="col-12 text-gray p-3 border-bottom">
    <div class="p-2">
      <span class="text-left"> Referral Code
        <i class="fas fa-info-circle"
        data-toggle="tooltip"
        data-placement="top" title=" You can Share this refferel code to earn one butterfly from Bolokobul">
        </i>
      </span>
      </div>
    </div>

    <div class="col-12 text-gray p-3 border-bottom">
      <div class="p-2">
        <span class=" text-left">  Your Code : <%= current_user.refferel_code.present? ? current_user.refferel_code : '' %> </span>
      </div>
    </div>
  </div>
</div>

app/views/marriage_profiles/_search_box.html.erb
<% if current_user.advanced_search == "enabled" %>
  <div class="col-md-3">
    <div class="container search-page-container p-3 ml-2">
      <div class="row">
        <div class="col-md-12 filter-container-content">
          <div class="filter-container-title">
            <div class="row col-md-12">
              <span class="p-2">
                Advanced Filter
              </span>
              <a href="<%= search_page_marriage_profile_path %>">
                <button id="reset_radio_btn"
                        class="btn btn-search btn-reset form-control ml-3">
                  Reset
                </button>
              </a>
            </div>
          </div>
          <div class="search-input-fields filter-input-fields">
            <div class="row form-group col-md-12 mb-0">
            </div>
            <%= form_tag search_marriage_profile_path do %>
              <div class="row form-group mx-1 mb-2">
                <hr class="filter-hr mb-1">
                <div class="col-md-12 filter-input-group px-0">
                  <%= label_tag :height %>
                  <br>
                  <%= radio_button_tag :height, "tier_1",
                                       params[:height] == "tier_1" ?
                                           true : false,
                                       {} %>  5'1"-5'4"
                  <br>
                  <%= radio_button_tag :height, "tier_2",
                                       params[:height] == "tier_2" ?
                                           true : false,
                                       {} %>  5'5"-5'8"
                  <br>
                  <%= radio_button_tag :height, "tier_3",
                                       params[:height] == "tier_3" ?
                                           true : false,
                                       {} %>  5'9"-6'0"
                  <br>
                  <%= radio_button_tag :height, "tier_4",
                                       params[:height] == "tier_4" ?
                                           true : false,
                                       {} %>  6'1"-6'5"
                  <br>
                </div>
              </div>
              <div class="row form-group mx-1 mb-2">
                <hr class="filter-hr mb-1">
                <div class="col-md-12 filter-input-group px-0">
                  <%= label_tag :marital_status %>
                  <br>
                  <% MarriageProfile.marital_statuses.each do |type, v| %>
                    <%= radio_button_tag :marital_status, type,
                                         params[:marital_status] == type ?
                                             true : false,
                                         {} %>  <%= type.titleize %>
                    <br>
                  <% end %>
                </div>
              </div>
              <div class="row form-group mx-1 mb-2">
                <hr class="filter-hr mb-1">
                <div class="col-md-12 filter-input-group px-0">
                  <%= label_tag :blood_group %>
                  <br>
                  <% MarriageProfile.blood_groups.each do |type, v| %>
                    <%= radio_button_tag :blood_group, type,
                                         params[:blood_group] == type ?
                                             true : false,
                                         {} %>  <%= type.upcase %>
                    <br>
                  <% end %>
                </div>
              </div>
              <div class="row form-group mx-1 mb-2">
                <hr class="filter-hr mb-1">
                <div class="col-md-12 filter-input-group px-0">
                  <%= label_tag :highest_education_level %>
                  <br>
                  <% MarriageProfile.highest_education_levels.each do |type, v| %>
                    <%= radio_button_tag :highest_education_level, type,
                                         params[:highest_education_level] == type ?
                                             true : false,
                                         {} %>  <%= type.titleize %>
                    <br>
                  <% end %>
                </div>
              </div>
              <div class="row form-group mx-1 mb-2">
                <hr class="filter-hr mb-1">
                <div class="col-md-12 filter-input-group px-0">
                  <%= label_tag :occupation %>
                  <br>
                  <div class="occupation-filter-inputs p-2">
                    <% Occupation.names.each do |type, v| %>
                      <%= radio_button_tag :occupation, type,
                                           params[:occupation] == type ?
                                               true : false,
                                           {} %>  <%= type.titleize %>
                      <br>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <div class="col-md-9">
    <div class="container search-page-container p-3">
          <div class="row">
            <div class="search-container-background">
              <%= image_tag 'mandala.svg', class: 'img-responsive' %>
            </div>
            <div class="col-md-12 search-container-content">
              <div class="search-container-title">
                <div class="row col-md-12 mx-1">
                  I am looking for...
                </div>
              </div>
              <div class="search-input-fields">
                <div class="row form-group col-md-12 mb-0">
                </div>
                <div class="row form-group mx-1 mb-3">
                  <div class="col-md-3 search-input-group">
                    <%= text_field_tag :age, params[:age].present? ? params[:age] : nil,
                                       placeholder: "Age",
                                       class:
                                           "form-control sign_up-input-field search-input" %>
                  </div>
                  <div class="col-md-3 search-input-group">
                    <%= select_tag :religion,
                                   options_for_select(MarriageProfile.religions
                                                          .map{|k, v| k.titleize},
                                                      ),
                                   prompt: params[:religion].present? ?
                                               params[:religion] : "Religion",
                                   class: "form-control sign_up-input-field search-input" %>
                    <i class="fa fa-sort-down search-drop-icon"></i>
                  </div>
                  <div class="col-md-3 search-input-group">
                    <%= select_tag :hometown,
                                   options_for_select(District.order(:name)
                                                          .pluck(:name)),
                                   prompt: params[:hometown].present? ?
                                               params[:hometown] : "Hometown",
                                   class: "form-control sign_up-input-field search-input" %>
                    <i class="fa fa-sort-down search-drop-icon"></i>
                  </div>
                  <div class="col-md-3 search-input-group">
                    <div class="text-center">
                      <button type="submit" class="btn btn-search form-control"> Search</button>
                    </div>
                  </div>
                </div>
    <% end %>
    </div>
    </div>
    </div>
    </div>
    <div class="d-sm-flex flex-sm-row ">
      <%= render 'home/dashboard/search_list', matches: @matches,
                 title: ""%>
    </div>
  </div>
<% else %>
  <div class="col-md-12">
    <div class="container search-page-container p-3">
      <div class="row">
        <div class="search-container-background">
          <%= image_tag 'mandala.svg', class: 'img-responsive' %>
        </div>
        <div class="col-md-12 search-container-content">
          <div class="search-container-title">
            <div class="row col-md-12 mx-1">
              <span class="p-2">
                I am looking for...
              </span>
              <a href="<%= privacy_settings_path%>">
                <button id="buy-adv-search"
                        class="btn btn-search btn-buy-adv-search form-control ml-3">
                  Enable Advanced Search
                </button>
              </a>
            </div>
          </div>
          <div class="search-input-fields">
            <div class="row form-group col-md-12 mb-0">
            </div>
            <%= form_tag search_marriage_profile_path do %>
              <div class="row form-group mx-1 mb-3">
                <div class="col-md-3 search-input-group">
                  <%= text_field_tag :age, params[:age].present? ? params[:age] : nil,
                                     placeholder: "Age",
                                     class:
                                         "form-control sign_up-input-field search-input" %>
                </div>
                <div class="col-md-3 search-input-group">
                  <%= select_tag :religion,
                                 options_for_select(MarriageProfile.religions
                                                        .map{|k, v| k.titleize},
                                                    ),
                                 prompt: params[:religion].present? ?
                                             params[:religion] : "Religion",
                                 class: "form-control sign_up-input-field search-input" %>
                  <i class="fa fa-sort-down search-drop-icon"></i>
                </div>
                <div class="col-md-3 search-input-group">
                  <%= select_tag :hometown,
                                 options_for_select(District.order(:name)
                                                        .pluck(:name)),
                                 prompt: params[:hometown].present? ?
                                             params[:hometown] : "Hometown",
                                 class: "form-control sign_up-input-field search-input" %>
                  <i class="fa fa-sort-down search-drop-icon"></i>
                </div>
                <div class="col-md-3 search-input-group">
                  <div class="text-center">
                    <button type="submit" class="btn btn-search form-control"> Search</button>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="container d-sm-flex flex-sm-row ">
      <%= render 'home/dashboard/search_list', matches: @matches,
                 title: ""%>
    </div>
  </div>
<% end %>

app/views/marriage_profiles/blocked_profiles.html.erb
<div class="container-fluid p-0 ">
  <div class="dashboard">
    <div class="container">
      <div class="d-sm-flex flex-sm-row privacy-settings">
        <%= render 'privacy_settings/privacy_left_sidebar' %>
        <%= render 'marriage_profiles/blocked_list', blocked_profiles: @blocked_profiles %>
      </div>
    </div>
  </div>
</div>

app/views/marriage_profiles/dashboard.html.erb
<div class="flash-msg-profile-change"></div>
<div class="container-fluid p-0 ">
  <div class="dashboard">
    <div class="container">
      <div class="d-sm-flex flex-sm-row ">
        <%= render 'home/dashboard/left_sidebar', marriage_profile: @marriage_profile %>
        <%= render 'home/dashboard/right_section', marriage_profile: @marriage_profile %>
      </div>
    </div>
  </div>
</div>

app/views/marriage_profiles/pending_profiles.html.erb
<div class="container-fluid p-0 ">
  <div class="dashboard">
    <div class="container">
      <div class="d-sm-flex flex-sm-row privacy-settings">
        <%= render 'privacy_settings/privacy_left_sidebar' %>
        <%= render 'marriage_profiles/pendin_list', pending_profiles: @pending_profiles %>
      </div>
    </div>
  </div>
</div>

app/views/marriage_profiles/update_about.js.erb
$('.about_marriage_profile').html("<%= escape_javascript(render 'about_marriage_profile', marriage_profile: @marriage_profile) %>");
$('#global_update_modal_sm').modal('hide');
$(".update-notice").html('<%= j render partial: "shared/flash_message", locals: { notice: flash[:notice] } %>');